"""empty message

Revision ID: 847aefe8f475
Revises: 
Create Date: 2023-08-21 14:25:33.909052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847aefe8f475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pen_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publisher_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('founding_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author_table.id'], name=op.f('fk_book_table_author_id_author_table')),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher_table.id'], name=op.f('fk_book_table_publisher_id_publisher_table')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_table')
    op.drop_table('publisher_table')
    op.drop_table('author_table')
    # ### end Alembic commands ###
