"""empty message

Revision ID: 002825f58300
Revises: 
Create Date: 2023-08-23 10:50:29.353499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002825f58300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_table.id'], name=op.f('fk_appointment_table_doctor_id_doctor_table')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_table.id'], name=op.f('fk_appointment_table_patient_id_patient_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_table')
    op.drop_table('patient_table')
    op.drop_table('doctor_table')
    # ### end Alembic commands ###
